name: htkc_utils
description: HTKC Utils is a reusable Flutter package that provides a collection of utility functions, classes, and widgets that can be used in any Flutter project.
version: 1.2.2
homepage: https://github.com/ChandraHemant/htkc_utils

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.3
  intl: ^0.18.1
  http: ^1.0.0
  nb_utils: ^4.4.12
  path_provider: ^2.0.15
  permission_handler: ^10.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  assets:
    - assets/
    - assets/app/
    - assets/icons/