name: htkc_utils
description: HTKC Utils is a reusable Flutter package that provides a collection of utility functions, classes, and widgets that can be used in any Flutter project.
version: 1.0.4
homepage: https://github.com/ChandraHemant/htkc_utils

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.1.0
  http: ^0.13.4
  intl: ^0.17.0
  flutter_neumorphic: ^3.0.3
  nb_utils: ^4.4.12
  permission_handler: ^9.0.2
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  assets:
    - assets/
    - assets/app/
    - assets/icons/