name: htkc_utils
description: HTKC Utils is a reusable Flutter package that provides a collection of utility functions, classes, and widgets that can be used in any Flutter project.
version: 1.3.5
homepage: https://github.com/ChandraHemant/htkc_utils

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cross_file: ^0.3.3+4
  cached_network_image: ^3.2.3
  flutter_image_compress: ^2.0.3
  image_compression: ^1.0.4
  intl: ^0.18.1
  get: ^4.6.5
  http: ^1.0.0
  path_provider: ^2.0.15
  permission_handler: ^10.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  assets:
    - assets/
    - assets/app/
    - assets/icons/