name: htkc_utils
description: HTKC Utils is a reusable Flutter package that provides a collection of utility functions, classes, and widgets that can be used in any Flutter project.
version: 1.4.8
homepage: https://github.com/ChandraHemant/htkc_utils

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cross_file: ^0.3.3+4
  cached_network_image: ^3.2.3
  flutter_image_compress: ^2.0.4
  image_compression: ^1.0.4
  intl: ^0.18.1
  get: ^4.6.5
  http: ^1.0.0
  path_provider: ^2.0.15
  permission_handler: ^10.4.2
  path_drawing: ^1.0.1

  diffutil_dart: ^3.0.0
  equatable: ^2.0.5
  flutter_chat_types: ^3.6.2
  flutter_link_previewer: ^3.2.2
  flutter_parsed_text: ^2.2.1
  meta: '>=1.8.0 <2.0.0'
  photo_view: ^0.14.0
  scroll_to_index: ^3.0.1
  url_launcher: ^6.1.12
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  assets:
    - packages/htkc_utils/assets/icon-arrow.png
    - packages/htkc_utils/assets/icon-attachment.png
    - packages/htkc_utils/assets/icon-delivered.png
    - packages/htkc_utils/assets/icon-document.png
    - packages/htkc_utils/assets/icon-error.png
    - packages/htkc_utils/assets/icon-seen.png
    - packages/htkc_utils/assets/icon-send.png
    - packages/htkc_utils/assets/2.0x/icon-arrow.png
    - packages/htkc_utils/assets/2.0x/icon-attachment.png
    - packages/htkc_utils/assets/2.0x/icon-delivered.png
    - packages/htkc_utils/assets/2.0x/icon-document.png
    - packages/htkc_utils/assets/2.0x/icon-error.png
    - packages/htkc_utils/assets/2.0x/icon-seen.png
    - packages/htkc_utils/assets/2.0x/icon-send.png
    - packages/htkc_utils/assets/3.0x/icon-arrow.png
    - packages/htkc_utils/assets/3.0x/icon-attachment.png
    - packages/htkc_utils/assets/3.0x/icon-delivered.png
    - packages/htkc_utils/assets/3.0x/icon-document.png
    - packages/htkc_utils/assets/3.0x/icon-error.png
    - packages/htkc_utils/assets/3.0x/icon-seen.png
    - packages/htkc_utils/assets/3.0x/icon-send.png

    - assets/
    - assets/app/
    - assets/icons/