name: htkc_utils
description: HTKC Utils is a reusable Flutter package that provides a collection of utility functions, classes, and widgets that can be used in any Flutter project.
version: 1.5.9
homepage: https://github.com/ChandraHemant/htkc_utils

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cross_file: ^0.3.3+4
  cached_network_image: ^3.2.3
  image_compression: ^1.0.4
  intl: ^0.19.0
  get: ^4.6.5
  http: ^1.2.0
  path_provider: ^2.0.15
  permission_handler: ^11.3.0
  path_drawing: ^1.0.1

  package_info_plus: ^6.0.0
  collection: ^1.17.2
  html: ^0.15.4

  diffutil_dart: ^4.0.1
  equatable: ^2.0.5
  flutter_chat_types: ^3.6.2
  flutter_link_previewer: ^3.2.2
  flutter_parsed_text: ^2.2.1
  meta: ^1.11.0
  photo_view: ^0.14.0
  scroll_to_index: ^3.0.1
  url_launcher: ^6.1.12
  visibility_detector: ^0.4.0+2

  # From fluttercommunity.dev: Get current device information from within the Flutter application.
  device_info_plus: ^9.0.2

  # From dart.dev: Platform independent access to information about the current operating system.
  os_detect: ^2.0.1

  # From Flutter Team: Wraps NSUserDefaults (on iOS) and SharedPreferences (on Android).
  shared_preferences: ^2.2.2

  # A dart library for comparing and incrementing version numbers with Semantic Versioning.
  version: ^3.0.2

  # A dart library for parsing, traversing, querying, transforming and building XML documents.
  xml: ^6.3.0

dev_dependencies:

  # From Dart Team: Mock library for Dart inspired by Mockito.
  mockito: ^5.4.3
  flutter_lints: ^3.0.1
  go_router: ^13.2.0

flutter:

  assets:
    - packages/htkc_utils/assets/icon-arrow.png
    - packages/htkc_utils/assets/icon-attachment.png
    - packages/htkc_utils/assets/icon-delivered.png
    - packages/htkc_utils/assets/icon-document.png
    - packages/htkc_utils/assets/icon-error.png
    - packages/htkc_utils/assets/icon-seen.png
    - packages/htkc_utils/assets/icon-send.png
    - packages/htkc_utils/assets/2.0x/icon-arrow.png
    - packages/htkc_utils/assets/2.0x/icon-attachment.png
    - packages/htkc_utils/assets/2.0x/icon-delivered.png
    - packages/htkc_utils/assets/2.0x/icon-document.png
    - packages/htkc_utils/assets/2.0x/icon-error.png
    - packages/htkc_utils/assets/2.0x/icon-seen.png
    - packages/htkc_utils/assets/2.0x/icon-send.png
    - packages/htkc_utils/assets/3.0x/icon-arrow.png
    - packages/htkc_utils/assets/3.0x/icon-attachment.png
    - packages/htkc_utils/assets/3.0x/icon-delivered.png
    - packages/htkc_utils/assets/3.0x/icon-document.png
    - packages/htkc_utils/assets/3.0x/icon-error.png
    - packages/htkc_utils/assets/3.0x/icon-seen.png
    - packages/htkc_utils/assets/3.0x/icon-send.png

    - assets/
    - assets/app/
    - assets/icons/